

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.spire.data.table.DataTable;
import com.spire.data.table.common.JdbcAdapter;
import com.spire.pdf.PdfDocument;
import com.spire.pdf.PdfPageBase;
import com.spire.pdf.graphics.PdfBrush;
import com.spire.pdf.graphics.PdfBrushes;
import com.spire.pdf.graphics.PdfLayoutResult;
import com.spire.pdf.graphics.PdfLayoutType;
import com.spire.pdf.graphics.PdfStringFormat;
import com.spire.pdf.graphics.PdfTextAlignment;
import com.spire.pdf.graphics.PdfTrueTypeFont;
import com.spire.pdf.tables.PdfTable;
import com.spire.pdf.tables.PdfTableDataSourceType;
import com.spire.pdf.tables.PdfTableLayoutFormat;
import java.awt.Color;
import java.io.*;
import java.io.PrintWriter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

import java.awt.geom.*;
import java.awt.*;
import java.sql.*;
import javax.swing.JFrame;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author marko
 */
public class Clients_Window extends javax.swing.JFrame {

    /**
     * Creates new form Clients_Window
     */
    public Clients_Window() {
        initComponents();
        SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        jLabel14.setText(dFormat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        jLabel15.setText(dtf.format(now));
        
        
        
        
        
        
          // border for title of the panel
        Border panel_title_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(235,125,22));
        jPanel_title.setBorder(panel_title_border);
        
        // border for jbuttons
        Border button_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(255,255,255));
        jButton_Add_Client.setBorder(button_border);
        jButton_Edit_Client.setBorder(button_border);
        jButton_Refresh_Client.setBorder(button_border);
        
        fillJTableWithClientsData();
        
    }
   
    public void ExportPdf(){
        try{
            String file_name="C:\\Users\\marko\\Desktop\\klijenti.pdf";
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(file_name));
            
            document.open();
            Paragraph para= new Paragraph("");
            
            document.close();
            
        }catch(Exception e){
            System.err.println(e);
        }
    }


     public void fillJTableWithClientsData(){
        P_CLIENT client = new P_CLIENT();
        ArrayList<P_CLIENT> clientsList= client.clientsList();
        
        // the jtable columns
        String[] colNames= {"id","Ime","Prezime","broj_telefona","mejl","adresa"};
        
        //the jtable row
        //workersList.size() size of arraylist
        //5 for number of colums in database
        Object[][] rows = new Object[clientsList.size()][6];
        
        //add data from the list to the rows
        for(int i =0; i<clientsList.size();i++){
            rows[i][0]=clientsList.get(i).getid();
            rows[i][1]=clientsList.get(i).getIme();
            rows[i][2]=clientsList.get(i).getPrezime();
            rows[i][3]=clientsList.get(i).getbroj_telefona();
            rows[i][4]=clientsList.get(i).getmejl();
            rows[i][5]=clientsList.get(i).getadresa();
        }
        DefaultTableModel model =new DefaultTableModel(rows, colNames);
        jTable1.setModel(model);
        //change jtable row height 
        jTable1.setRowHeight(50);
        //background color when value selected
        jTable1.setSelectionBackground(Color.red);
        //change jtable width
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(55);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(55);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(55);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(122);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(122);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Ime = new javax.swing.JTextField();
        jTextField_id = new javax.swing.JTextField();
        jTextField_broj_telefona = new javax.swing.JTextField();
        jTextField_Prezime = new javax.swing.JTextField();
        jButton_Edit_Client = new javax.swing.JButton();
        jButton_Remove_Clients = new javax.swing.JButton();
        jButton_Add_Client = new javax.swing.JButton();
        jButton_Refresh_Client = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_mejl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField_adresa = new javax.swing.JTextField();
        jButton_export = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Date:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Time:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("jLabel3");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 178, 48));

        jPanel_title.setBackground(new java.awt.Color(96, 90, 223));

        jLabel1.setBackground(new java.awt.Color(246, 145, 16));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Klijenti");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo3_2.jpg"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(391, 391, 391))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Prezime:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("id:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mejl:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ime:");

        jButton_Edit_Client.setBackground(new java.awt.Color(102, 0, 255));
        jButton_Edit_Client.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Edit_Client.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit_Client.setText("edit");
        jButton_Edit_Client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_ClientActionPerformed(evt);
            }
        });

        jButton_Remove_Clients.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Remove_Clients.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Remove_Clients.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_Clients.setText("remove");
        jButton_Remove_Clients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_ClientsActionPerformed(evt);
            }
        });

        jButton_Add_Client.setBackground(new java.awt.Color(255, 102, 102));
        jButton_Add_Client.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Add_Client.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_Client.setText("add");
        jButton_Add_Client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ClientActionPerformed(evt);
            }
        });

        jButton_Refresh_Client.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Refresh_Client.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Refresh_Client.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Refresh_Client.setText("refresh");
        jButton_Refresh_Client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Refresh_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Refresh_ClientActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Broj Telefona:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Adresa:");

        jButton_export.setBackground(new java.awt.Color(255, 102, 102));
        jButton_export.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_export.setForeground(new java.awt.Color(255, 255, 255));
        jButton_export.setText("export");
        jButton_export.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exportActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Date:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Time:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("jLabel3");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_adresa, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jTextField_Prezime)
                            .addComponent(jTextField_Ime)
                            .addComponent(jTextField_id)
                            .addComponent(jTextField_mejl)
                            .addComponent(jTextField_broj_telefona))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton_Add_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton_Edit_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton_Remove_Clients, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton_Refresh_Client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jButton_export, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(43, 43, 43))
            .addComponent(jPanel_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Ime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Prezime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_broj_telefona, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_mejl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_adresa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Edit_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Remove_Clients, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Refresh_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Add_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_export, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Edit_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_ClientActionPerformed
        // to edit selected values by typing the id of the value you want to edit
        int id = Integer.valueOf(jTextField_id.getText());
        String Ime = jTextField_Ime.getText();
        String Prezime = jTextField_Prezime.getText();
        String broj_telefona = jTextField_broj_telefona.getText();
        String mejl = jTextField_mejl.getText();
        String adresa = jTextField_adresa.getText();

        P_CLIENT client = new P_CLIENT();
        
        try {
            

            if(Ime.trim().equals("") || Prezime.trim().equals("") || broj_telefona.trim().equals("") || jTextField_mejl.getText().trim().equals("")||adresa.trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter required--id Ime, Prezime, broj telefon, mejl i adresu","to Edit Client", 1);
            }else {
                int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to edit this worker","Edited worker",JOptionPane.YES_NO_OPTION);
                if (yes_or_no == JOptionPane.YES_OPTION){
                    if(client.editClientdata(new P_CLIENT(id , Ime, Prezime, broj_telefona, mejl, adresa))) {
                        JOptionPane.showMessageDialog(null, "Worker edited in system","Edit Worker", 1);

                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Worker not edited to system","Maybe id field is not empty or values incorect", 2);
                    }
                }
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage()+ "Enter required information--ID_Zap Ime, Prezime, Radna_uloga i ID_Operacije to edit ","Invalid", 0);
        }
    }//GEN-LAST:event_jButton_Edit_ClientActionPerformed

    private void jButton_Remove_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_ClientsActionPerformed
        // to remove value from picked id

        P_CLIENT client = new P_CLIENT();

        try {
            int id = Integer.valueOf(jTextField_id.getText());

            if( jTextField_id.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter id","Da uklonis klijenta", 1);
            }else {
                int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to delete this worker","Deleted worker",JOptionPane.YES_NO_OPTION);
                if (yes_or_no == JOptionPane.YES_OPTION){

                    if(client.deleteclientdata(new P_CLIENT(id,"","","","",""))) {
                        JOptionPane.showMessageDialog(null, "Klijent uklonjen","Remove Worker", 1);

                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Klijent nije uklonjen iz sistema","Mozda polja nisu tacna", 2);
                    }
                }
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage()+ "Enter required information--ID_Zap to remove worker ","Invalid", 0);
        }
    }//GEN-LAST:event_jButton_Remove_ClientsActionPerformed

    private void jButton_Add_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ClientActionPerformed
        // add new values also id auto increments

        //get the clients data
        String Ime = jTextField_Ime.getText();
        String Prezime = jTextField_Prezime.getText();
        String broj_telefona = jTextField_broj_telefona.getText();
        String mejl = jTextField_mejl.getText();
        String adresa = jTextField_adresa.getText();

        P_CLIENT client = new P_CLIENT();

        //before inserting new client we need to check if fields are correct
        try {
            

            if(Ime.trim().equals("") || Prezime.trim().equals("") || broj_telefona.trim().equals("") || mejl.trim().equals("")|| adresa.trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter required information--Ime, Prezime, broj_telefona, mejl, adresu","Da bih dodao klijenta", 1);
            }else {
                int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to add this client","Added client",JOptionPane.YES_NO_OPTION);
                if (yes_or_no == JOptionPane.YES_OPTION){
                    if(client.addClientdata(new P_CLIENT(0, Ime, Prezime, broj_telefona, mejl, adresa))) {
                        JOptionPane.showMessageDialog(null, "New Client added to system","Add Client", 1);

                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Client not added to system","Maybe id field is not empty or values incorect", 2);
                    }
                }
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage()+ "Enter required information--Ime, Prezime, broj_telefona, mejl, adresu ","Invalid", 0);
        }

    }//GEN-LAST:event_jButton_Add_ClientActionPerformed

    private void jButton_Refresh_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Refresh_ClientActionPerformed
        // To refresh the window by calling the fill function to see new values
       fillJTableWithClientsData();

    }//GEN-LAST:event_jButton_Refresh_ClientActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // when value selected in jtable to add to text fields
        int selectedRowIndex = jTable1.getSelectedRow();
        jTextField_id.setText(jTable1.getValueAt(selectedRowIndex, 0).toString());
        jTextField_Ime.setText(jTable1.getValueAt(selectedRowIndex, 1).toString());
        jTextField_Prezime.setText(jTable1.getValueAt(selectedRowIndex, 2).toString());
        jTextField_broj_telefona.setText(jTable1.getValueAt(selectedRowIndex, 3).toString());
        jTextField_mejl.setText(jTable1.getValueAt(selectedRowIndex, 4).toString());
        jTextField_adresa.setText(jTable1.getValueAt(selectedRowIndex, 5).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exportActionPerformed

        String id=jTextField_id.getText();
        String Ime=jTextField_Ime.getText();
        String Prezime=jTextField_Prezime.getText();
        String Broj_telefona=jTextField_broj_telefona.getText();
        String mejl=jTextField_mejl.getText();
        String adresa=jTextField_adresa.getText();
        String path="C:\\Users\\marko\\Desktop\\Klijenti.pdf";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                                Krojac(Lista Klijenta)\n                                  Contact Number:(+381)111111\n\n");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("Date:"+jLabel14.getText()+"\n Time: "+jLabel15.getText()+"\n\n");
            doc.add(paragraph2);
            PdfPTable tbl = new PdfPTable(6);
            tbl.addCell("id");
            tbl.addCell("Ime");
            tbl.addCell("Prezime");
            tbl.addCell("Broj_telefona:");
            tbl.addCell("Mejl:");
            tbl.addCell("adresa:");
            
            for (int i=0;i<jTable1.getRowCount();i++){
                String n=jTable1.getValueAt(i, 0).toString();
                String d=jTable1.getValueAt(i, 1).toString();
                String r=jTable1.getValueAt(i, 2).toString();
                String q=jTable1.getValueAt(i, 3).toString();
                String s=jTable1.getValueAt(i, 4).toString();
                String a=jTable1.getValueAt(i, 5).toString();
                tbl.addCell(n);
                tbl.addCell(d);
                tbl.addCell(r);
                tbl.addCell(q);
                tbl.addCell(s);
                tbl.addCell(a);
            }
            doc.add(tbl);
            Paragraph paragraph3= new Paragraph("\n\nThank you for Visiting !Please Come again\nKrojac");
            
            doc.add(paragraph3);
            JOptionPane.showMessageDialog(null,"Lista zaposlenih napravljena");
            setVisible(true);
            
            new Clients_Window().setVisible(true);
            this.dispose();
            
        }catch (Exception e){
            
        }
        doc.close();
        
        /*
         try {
    PrintWriter pw= new PrintWriter(new File("C:\\Users\\marko\\Desktop\\Clients.txt"));
    StringBuilder sb=new StringBuilder();
    PreparedStatement ps;
    ResultSet rs=null;
 
    String query="select * from klijenti";
     ps = Connect_db.getTheconnection().prepareStatement(query);
    rs=ps.executeQuery();
 
    while(rs.next()){
     sb.append("ID: "); 
     sb.append(rs.getInt("id"));
     sb.append("   "); 
     sb.append("Ime: ");
     sb.append(rs.getString("Ime"));
     sb.append("   ");
     sb.append("Prezime: ");
     sb.append(rs.getString("Prezime"));
     sb.append("   ");
     sb.append("Broj telefona: ");
     sb.append(rs.getString("broj_telefona"));
     sb.append("   ");
     sb.append("Mejl: ");
     sb.append(rs.getString("mejl"));
     sb.append("   ");
     sb.append("Adresa: ");
     sb.append(rs.getString("adresa"));
     sb.append("\r\n");
    }
 
    pw.write(sb.toString());
    pw.close();
    System.out.println("finished");
    JOptionPane.showMessageDialog(null,"Exported all values to file ","Done", 0);
 
   } catch (Exception e) {
    // TODO: handle exception
   } 
        */
    }//GEN-LAST:event_jButton_exportActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        Main_Window mainform = new Main_Window();
               mainform.setVisible(true);
               mainform.pack();
               mainform.setExtendedState(JFrame.MAXIMIZED_BOTH);  // to open in full screen
               //to close login window
               this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clients_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Client;
    private javax.swing.JButton jButton_Edit_Client;
    private javax.swing.JButton jButton_Refresh_Client;
    private javax.swing.JButton jButton_Remove_Clients;
    private javax.swing.JButton jButton_export;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Ime;
    private javax.swing.JTextField jTextField_Prezime;
    private javax.swing.JTextField jTextField_adresa;
    private javax.swing.JTextField jTextField_broj_telefona;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_mejl;
    // End of variables declaration//GEN-END:variables
}
