
import java.awt.*;
import javax.swing.*;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author marko
 */
public class Main_Window extends javax.swing.JFrame {

    /**
     * Creates new form Main_Window
     */
    public Main_Window() {
        initComponents();
        
        //set the logo picture
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.jpg")));
        
        //set bborder for logo
        Border logo_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.green);
        jLabel_logo.setBorder(logo_border);
        
        // set border for name of the main window
        Border name_border = BorderFactory.createMatteBorder(0, 0, 3, 0, Color.white);
        jLabel_name.setBorder(name_border);
        // set border for varibles in main window
        /* set border for name of the main window( can be done with less code for example 
               Border menu_items_border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.white); 
               jLabel_postupak.setBorder(menu_items_border);
               jLabel_zahvat.setBorder(menu_items_border);
               itd, personal prefrence since for me its easier to read and if i want to have diffrent colors for diffrent items
               */
        //for postupak
        Border postupak_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabel_postupak.setBorder(postupak_border);
        //za zahvat
        Border zahvat_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabel_Proizvodi.setBorder(zahvat_border);
        //za trosak
        Border trosak_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabel_trosak.setBorder(trosak_border);
        //za evident
        Border evident_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabel_online.setBorder(evident_border);
        //za helanke
        Border helanke_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabel_helanke.setBorder(helanke_border);
        //za zaposlene
        Border zaposleni_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabel_zaposleni.setBorder(zaposleni_border);
         //za koristite se
        Border koristiti_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabel_Sign_out.setBorder(koristiti_border);
        Border prodaja_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabel_prodaja.setBorder(prodaja_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_logo = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_postupak = new javax.swing.JLabel();
        jLabel_Proizvodi = new javax.swing.JLabel();
        jLabel_online = new javax.swing.JLabel();
        jLabel_trosak = new javax.swing.JLabel();
        jLabel_zaposleni = new javax.swing.JLabel();
        jLabel_Sign_out = new javax.swing.JLabel();
        jLabel_helanke = new javax.swing.JLabel();
        jLabel_prodaja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));

        jLabel_logo.setBackground(new java.awt.Color(102, 153, 255));
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.jpg"))); // NOI18N
        jLabel_logo.setOpaque(true);

        jLabel_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_name.setText("Krojac");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 321, -1));

        jLabel_postupak.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_postupak.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_postupak.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_postupak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_postupak.setText("Potrebno vreme operacija");
        jLabel_postupak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_postupak.setOpaque(true);
        jLabel_postupak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_postupakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_postupakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_postupakMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_postupak, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, -1, 42));

        jLabel_Proizvodi.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_Proizvodi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Proizvodi.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Proizvodi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Proizvodi.setText("Proizvodi");
        jLabel_Proizvodi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Proizvodi.setOpaque(true);
        jLabel_Proizvodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ProizvodiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ProizvodiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ProizvodiMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_Proizvodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, 297, 42));

        jLabel_online.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_online.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_online.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_online.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_online.setText("Online prodaja");
        jLabel_online.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_online.setOpaque(true);
        jLabel_online.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_onlineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_onlineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_onlineMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_online, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 220, 297, 42));

        jLabel_trosak.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_trosak.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_trosak.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_trosak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_trosak.setText("Klijenti");
        jLabel_trosak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_trosak.setOpaque(true);
        jLabel_trosak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_trosakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_trosakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_trosakMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_trosak, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 172, 297, 42));

        jLabel_zaposleni.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_zaposleni.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_zaposleni.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_zaposleni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_zaposleni.setText("Zaposleni");
        jLabel_zaposleni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_zaposleni.setOpaque(true);
        jLabel_zaposleni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_zaposleniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_zaposleniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_zaposleniMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_zaposleni, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 318, 297, 42));

        jLabel_Sign_out.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_Sign_out.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Sign_out.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Sign_out.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Sign_out.setText("Sign out");
        jLabel_Sign_out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Sign_out.setOpaque(true);
        jLabel_Sign_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Sign_outMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Sign_outMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Sign_outMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_Sign_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 427, 297, 42));

        jLabel_helanke.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_helanke.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_helanke.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_helanke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_helanke.setText("Racun");
        jLabel_helanke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_helanke.setOpaque(true);
        jLabel_helanke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_helankeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_helankeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_helankeMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_helanke, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 269, 297, 42));

        jLabel_prodaja.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_prodaja.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_prodaja.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_prodaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_prodaja.setText("Prodaja");
        jLabel_prodaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_prodaja.setOpaque(true);
        jLabel_prodaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_prodajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_prodajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_prodajaMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_prodaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 372, 297, 42));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 681, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_postupakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_postupakMouseEntered
        
        //to change color when mouse is over the varible
        
        jLabel_postupak.setBackground(Color.white);
        jLabel_postupak.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_postupakMouseEntered

    private void jLabel_postupakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_postupakMouseExited
       
        //to change color when mouse is leaves the varible
 
        jLabel_postupak.setBackground(new Color(102,102,102));
        jLabel_postupak.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_postupakMouseExited

    private void jLabel_ProizvodiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ProizvodiMouseEntered
        //to change color when mouse is over the varible(copy pasted from postupak)
        
        jLabel_Proizvodi.setBackground(Color.white);
        jLabel_Proizvodi.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_ProizvodiMouseEntered

    private void jLabel_ProizvodiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ProizvodiMouseExited
        //to change color when mouse is leaves the varible (also copy paste from postupak)
 
        jLabel_Proizvodi.setBackground(new Color(102,102,102));
        jLabel_Proizvodi.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_ProizvodiMouseExited

    private void jLabel_trosakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_trosakMouseEntered
        //to change color when mouse is over the varible(copy pasted from postupak)
        
        jLabel_trosak.setBackground(Color.white);
        jLabel_trosak.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_trosakMouseEntered

    private void jLabel_trosakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_trosakMouseExited
      //to change color when mouse is leaves the varible (also copy paste from postupak)
 
        jLabel_trosak.setBackground(new Color(102,102,102));
        jLabel_trosak.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_trosakMouseExited

    private void jLabel_onlineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_onlineMouseEntered
      //to change color when mouse is over the varible(copy pasted from postupak)
        
        jLabel_online.setBackground(Color.white);
        jLabel_online.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_onlineMouseEntered

    private void jLabel_onlineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_onlineMouseExited
        //to change color when mouse is leaves the varible (also copy paste from postupak)
 
        jLabel_online.setBackground(new Color(102,102,102));
        jLabel_online.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_onlineMouseExited

    private void jLabel_helankeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_helankeMouseEntered
         //to change color when mouse is over the varible(copy pasted from postupak)
        
        jLabel_helanke.setBackground(Color.white);
        jLabel_helanke.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_helankeMouseEntered

    private void jLabel_helankeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_helankeMouseExited
        //to change color when mouse is leaves the varible (also copy paste from postupak)
 
        jLabel_helanke.setBackground(new Color(102,102,102));
        jLabel_helanke.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_helankeMouseExited

    private void jLabel_zaposleniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_zaposleniMouseEntered
        //to change color when mouse is over the varible(copy pasted from postupak)
        
        jLabel_zaposleni.setBackground(Color.white);
        jLabel_zaposleni.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_zaposleniMouseEntered

    private void jLabel_zaposleniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_zaposleniMouseExited
         //to change color when mouse is leaves the varible (also copy paste from postupak)
 
        jLabel_zaposleni.setBackground(new Color(102,102,102));
        jLabel_zaposleni.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_zaposleniMouseExited

    private void jLabel_Sign_outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Sign_outMouseEntered
       //to change color when mouse is over the varible(copy pasted from postupak)
        
        jLabel_Sign_out.setBackground(Color.white);
        jLabel_Sign_out.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_Sign_outMouseEntered

    private void jLabel_Sign_outMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Sign_outMouseExited
         //to change color when mouse is leaves the varible (also copy paste from postupak)
 
        jLabel_Sign_out.setBackground(new Color(102,102,102));
        jLabel_Sign_out.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_Sign_outMouseExited

    private void jLabel_postupakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_postupakMouseClicked
       // to open postupak formu
       
      Postupak_Window typeform = new Postupak_Window();
      typeform.setVisible(true);
      typeform.pack();
      typeform.setLocationRelativeTo(null);
      typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      this.dispose();
    }//GEN-LAST:event_jLabel_postupakMouseClicked

    private void jLabel_zaposleniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_zaposleniMouseClicked
        // to open Zaposleni Window
        Zaposleni_Window worker = new Zaposleni_Window();
      worker.setVisible(true);
      worker.pack();
      worker.setLocationRelativeTo(null);
      worker.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      this.dispose();
    }//GEN-LAST:event_jLabel_zaposleniMouseClicked

    private void jLabel_ProizvodiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ProizvodiMouseClicked
       Proizvodi_Window product = new Proizvodi_Window();
      product.setVisible(true);
      product.pack();
      product.setLocationRelativeTo(null);
      product.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      this.dispose();
    }//GEN-LAST:event_jLabel_ProizvodiMouseClicked

    private void jLabel_Sign_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Sign_outMouseClicked
       Login_Window rgf = new Login_Window();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_Sign_outMouseClicked

    private void jLabel_trosakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_trosakMouseClicked
       Clients_Window client = new Clients_Window();
      client.setVisible(true);
      client.pack();
      client.setLocationRelativeTo(null);
      client.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      this.dispose();
    }//GEN-LAST:event_jLabel_trosakMouseClicked

    private void jLabel_onlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_onlineMouseClicked
       Placeholder1_Window online = new Placeholder1_Window();
      online.setVisible(true);
      online.pack();
      online.setLocationRelativeTo(null);
      online.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      this.dispose();
    }//GEN-LAST:event_jLabel_onlineMouseClicked

    private void jLabel_prodajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prodajaMouseClicked
        Sale_Window inperson = new Sale_Window();
      inperson.setVisible(true);
      inperson.pack();
      inperson.setLocationRelativeTo(null);
      inperson.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      this.dispose();
    }//GEN-LAST:event_jLabel_prodajaMouseClicked

    private void jLabel_prodajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prodajaMouseEntered
       jLabel_prodaja.setBackground(Color.white);
        jLabel_prodaja.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jLabel_prodajaMouseEntered

    private void jLabel_prodajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prodajaMouseExited
        jLabel_prodaja.setBackground(new Color(102,102,102));
        jLabel_prodaja.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_prodajaMouseExited

    private void jLabel_helankeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_helankeMouseClicked
        Billing bill = new Billing();
      bill.setVisible(true);
      bill.pack();
      bill.setLocationRelativeTo(null);
      bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_helankeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Proizvodi;
    private javax.swing.JLabel jLabel_Sign_out;
    private javax.swing.JLabel jLabel_helanke;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_online;
    private javax.swing.JLabel jLabel_postupak;
    private javax.swing.JLabel jLabel_prodaja;
    private javax.swing.JLabel jLabel_trosak;
    private javax.swing.JLabel jLabel_zaposleni;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
