
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.spire.data.table.DataTable;
import com.spire.data.table.common.JdbcAdapter;
import com.spire.pdf.PdfDocument;
import com.spire.pdf.PdfPageBase;
import com.spire.pdf.graphics.PdfBrush;
import com.spire.pdf.graphics.PdfBrushes;
import com.spire.pdf.graphics.PdfLayoutResult;
import com.spire.pdf.graphics.PdfLayoutType;
import com.spire.pdf.graphics.PdfStringFormat;
import com.spire.pdf.graphics.PdfTextAlignment;
import com.spire.pdf.graphics.PdfTrueTypeFont;
import com.spire.pdf.tables.PdfTable;
import com.spire.pdf.tables.PdfTableDataSourceType;
import com.spire.pdf.tables.PdfTableLayoutFormat;
import java.awt.Color;
import java.io.*;
import java.io.PrintWriter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import java.awt.geom.*;
import java.awt.*;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author marko
 */
public class Placeholder1_Window extends javax.swing.JFrame {

    /**
     * Creates new form Placeholder1_Window
     */
    P_type type = new P_type();
    HashMap<String, Integer> map = type.getTypesMap();
    
    
    public Placeholder1_Window() {
        initComponents();
        
        
          SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date date = new java.util.Date();
        jLabel14.setText(dFormat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        jLabel15.setText(dtf.format(now));
        // border for title of the panel
        Border panel_title_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(26,138,32));
        jPanel_title.setBorder(panel_title_border);
        
        // border for jbuttons
        Border button_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(255,255,255));
        jButton_Add_online_sale.setBorder(button_border);
        jButton_Edit_online_sale.setBorder(button_border);
        jButton_Remove_online_sale.setBorder(button_border);
        jButton_show_online_sale.setBorder(button_border);
        
        bindCombo();
    }
    
    public void bindCombo(){
        
        
        
        for(String s : map.keySet())
        {
            jComboBox_type.addItem(s);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_Client_id = new javax.swing.JTextField();
        jTextField_Due_date = new javax.swing.JTextField();
        jButton_Edit_online_sale = new javax.swing.JButton();
        jButton_Remove_online_sale = new javax.swing.JButton();
        jButton_Add_online_sale = new javax.swing.JButton();
        jButton_show_online_sale = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton_search = new javax.swing.JButton();
        jComboBox_type = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSpinner_kolicina = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_shipping_adress = new javax.swing.JTextArea();
        jCheckBox_brzina = new javax.swing.JCheckBox();
        jCheckBox_vreme = new javax.swing.JCheckBox();
        jCheck_vul = new javax.swing.JCheckBox();
        jCheck_leather = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jSpinner_materijali = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_Export_all = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(75, 192, 18));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_title.setBackground(new java.awt.Color(65, 160, 10));

        jLabel1.setBackground(new java.awt.Color(65, 160, 10));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PlaceHolder");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo3_2.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 110));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nacin dostave:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 220, 140, 36));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("id proizvoda:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 119, 140, 36));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cena:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 318, 66, 36));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tip:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 167, 54, 37));
        jPanel1.add(jTextField_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 122, 114, 36));
        jPanel1.add(jTextField_Client_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 269, 287, 36));
        jPanel1.add(jTextField_Due_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 223, 287, 36));

        jButton_Edit_online_sale.setBackground(new java.awt.Color(102, 0, 255));
        jButton_Edit_online_sale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Edit_online_sale.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit_online_sale.setText("edit");
        jButton_Edit_online_sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit_online_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_online_saleActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Edit_online_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 174, 61));

        jButton_Remove_online_sale.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Remove_online_sale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Remove_online_sale.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_online_sale.setText("remove");
        jButton_Remove_online_sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove_online_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_online_saleActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Remove_online_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 174, 61));

        jButton_Add_online_sale.setBackground(new java.awt.Color(255, 102, 102));
        jButton_Add_online_sale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Add_online_sale.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_online_sale.setText("add");
        jButton_Add_online_sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_online_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_online_saleActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Add_online_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 174, 61));

        jButton_show_online_sale.setBackground(new java.awt.Color(0, 153, 153));
        jButton_show_online_sale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_show_online_sale.setForeground(new java.awt.Color(255, 255, 255));
        jButton_show_online_sale.setText("Show properties");
        jButton_show_online_sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_show_online_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_online_saleActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_show_online_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, 195, 61));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ID klijenta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 266, 110, 36));
        jPanel1.add(jTextField_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 321, 287, 36));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Adresa dostave:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 154, 36));

        jButton_search.setBackground(new java.awt.Color(0, 0, 0));
        jButton_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_search.setText("Search");
        jButton_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 121, 166, 39));

        jComboBox_type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jComboBox_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 167, 287, 36));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Opis ili komentar:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 171, -1));

        jSpinner_kolicina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSpinner_kolicina.setModel(new javax.swing.SpinnerNumberModel(0, 0, 700, 1));
        jPanel1.add(jSpinner_kolicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 86, 36));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Kolicina Proizvoda:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 171, -1));

        jTextArea_shipping_adress.setColumns(20);
        jTextArea_shipping_adress.setRows(5);
        jScrollPane1.setViewportView(jTextArea_shipping_adress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 290, 136));

        jCheckBox_brzina.setBackground(new java.awt.Color(75, 192, 18));
        jCheckBox_brzina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox_brzina.setText("Dostupno odmah");
        jPanel1.add(jCheckBox_brzina, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, -1, -1));

        jCheckBox_vreme.setBackground(new java.awt.Color(75, 192, 18));
        jCheckBox_vreme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox_vreme.setText("Brza dostava");
        jPanel1.add(jCheckBox_vreme, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, -1, -1));

        jCheck_vul.setBackground(new java.awt.Color(75, 192, 18));
        jCheck_vul.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheck_vul.setText("Vuna");
        jPanel1.add(jCheck_vul, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, -1, -1));

        jCheck_leather.setBackground(new java.awt.Color(75, 192, 18));
        jCheck_leather.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheck_leather.setText("Koža");
        jPanel1.add(jCheck_leather, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Broj razlicitih materijala:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 220, -1));

        jSpinner_materijali.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSpinner_materijali.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        jPanel1.add(jSpinner_materijali, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 86, 36));

        jTextArea_description.setColumns(20);
        jTextArea_description.setRows(5);
        jScrollPane2.setViewportView(jTextArea_description);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 380, 136));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Date:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 550, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("jLabel3");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 550, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Time:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("jLabel4");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 610, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, 10, 10));

        jButton_Export_all.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Export_all.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Export_all.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Export_all.setText("Export all values to pdf");
        jButton_Export_all.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Export_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Export_allActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Export_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, 430, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Edit_online_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_online_saleActionPerformed
       try {
        int id_proizvoda=Integer.valueOf(jTextField_id.getText());  
        int Tip = map.get(jComboBox_type.getSelectedItem().toString()); 
        String Nacin_dostave = jTextField_Due_date.getText();
        int id_klijenta=Integer.valueOf(jTextField_Client_id.getText()); 
        int Cena=Integer.valueOf(jTextField_price.getText()); 
        String Adresa_dostave= jTextArea_shipping_adress.getText(); 
        int Kolicina_Proizvoda=Integer.valueOf(jSpinner_kolicina.getValue().toString()); 
        int Broj_razlicitih_materijala=Integer.valueOf(jSpinner_materijali.getValue().toString()); 
        String Opis_komentar= jTextArea_description.getText(); 
        boolean haveDostupno_odmah=false;
        boolean haveBrza_dostava=false;
        boolean haveKoža=false;
        boolean haveVuna=false;
        //check if the sale is/has availability, fast shipping, is it lether or Wool 
        if(jCheckBox_brzina.isSelected() ) haveDostupno_odmah=true;
        if(jCheckBox_vreme.isSelected() ) haveBrza_dostava=true;
        if(jCheck_leather.isSelected() ) haveKoža=true;
        if(jCheck_vul.isSelected() ) haveVuna=true;
        
        boolean Dostupno_odmah; 
        boolean Brza_dostava; 
        boolean Koža; 
        boolean Vuna;
        
        P_PLACE sale= new P_PLACE(id_proizvoda, Tip, Nacin_dostave, id_klijenta, Cena, Adresa_dostave, Kolicina_Proizvoda, Broj_razlicitih_materijala, Opis_komentar, haveDostupno_odmah, haveBrza_dostava, haveKoža, haveVuna);
        
        int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to edit this sale","Edited sale",JOptionPane.YES_NO_OPTION);
                if (yes_or_no == JOptionPane.YES_OPTION){
        if (new P_PLACE().editnewsale(sale)){
            JOptionPane.showMessageDialog(null, "New sale edited in system","Edit sale", 1);
        }
        else {
                        JOptionPane.showMessageDialog(null, "Sale not edited in system","Maybe fields are incorrect", 2);
                    }
                }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage()+ "Error ","Error", 0);
        }
    }//GEN-LAST:event_jButton_Edit_online_saleActionPerformed

    private void jButton_Remove_online_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_online_saleActionPerformed
         

        try {
            int id_proizvoda=Integer.valueOf(jTextField_id.getText());  
        int Tip = map.get(jComboBox_type.getSelectedItem().toString()); 
        String Nacin_dostave = jTextField_Due_date.getText();
        int id_klijenta=Integer.valueOf(jTextField_Client_id.getText()); 
        int Cena=Integer.valueOf(jTextField_price.getText()); 
        String Adresa_dostave= jTextArea_shipping_adress.getText(); 
        int Kolicina_Proizvoda=Integer.valueOf(jSpinner_kolicina.getValue().toString()); 
        int Broj_razlicitih_materijala=Integer.valueOf(jSpinner_materijali.getValue().toString()); 
        String Opis_komentar= jTextArea_description.getText(); 
        boolean haveDostupno_odmah=false;
        boolean haveBrza_dostava=false;
        boolean haveKoža=false;
        boolean haveVuna=false;
        //check if the sale is/has availability, fast shipping, is it lether or Wool 
        if(jCheckBox_brzina.isSelected() ) haveDostupno_odmah=true;
        if(jCheckBox_vreme.isSelected() ) haveBrza_dostava=true;
        if(jCheck_leather.isSelected() ) haveKoža=true;
        if(jCheck_vul.isSelected() ) haveVuna=true;
        
        boolean Dostupno_odmah; 
        boolean Brza_dostava; 
        boolean Koža; 
        boolean Vuna;
            P_PLACE sale = new P_PLACE(id_proizvoda, Tip, Nacin_dostave, id_klijenta, Cena, Adresa_dostave, Kolicina_Proizvoda, Broj_razlicitih_materijala, Opis_komentar, haveDostupno_odmah, haveBrza_dostava, haveKoža, haveVuna);
             

            if( jTextField_id.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Enter id","Da uklonis prodaju", 1);
            }else {
                int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to delete this sale","Deleted sale",JOptionPane.YES_NO_OPTION);
                if (yes_or_no == JOptionPane.YES_OPTION){

                    if(new P_PLACE().removenewsale(sale)) {
                        JOptionPane.showMessageDialog(null, "Klijent uklonjen","Remove Worker", 1);
                jTextField_id.setText("");
                jComboBox_type.setSelectedIndex(0);
                jTextField_Due_date.setText("");
                jTextField_Client_id.setText("");
                jTextField_price.setText("");
                jTextArea_shipping_adress.setText("");
                jSpinner_kolicina.setValue(0);
                jSpinner_materijali.setValue(0);
                jTextArea_description.setText("");
                jCheckBox_brzina.setSelected(false); 
                jCheckBox_vreme.setSelected(false);    
                jCheck_leather.setSelected(false);
                jCheck_vul.setSelected(false);
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Klijent nije uklonjen iz sistema","Mozda polja nisu tacna", 2);
                    }
                }
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage()+ "Enter required information--ID_Zap to remove worker ","Invalid", 0);
        }
    }//GEN-LAST:event_jButton_Remove_online_saleActionPerformed

    private void jButton_Add_online_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_online_saleActionPerformed
        // add new sale also id auto increments
        try {
            
        int Tip = map.get(jComboBox_type.getSelectedItem().toString()); 
        String Nacin_dostave = jTextField_Due_date.getText();
        int id_klijenta=Integer.valueOf(jTextField_Client_id.getText()); 
        int Cena=Integer.valueOf(jTextField_price.getText()); 
        String Adresa_dostave= jTextArea_shipping_adress.getText(); 
        int Kolicina_Proizvoda=Integer.valueOf(jSpinner_kolicina.getValue().toString()); 
        int Broj_razlicitih_materijala=Integer.valueOf(jSpinner_materijali.getValue().toString()); 
        String Opis_komentar= jTextArea_description.getText(); 
        boolean haveDostupno_odmah=false;
        boolean haveBrza_dostava=false;
        boolean haveKoža=false;
        boolean haveVuna=false;
        //check if the sale is/has availability, fast shipping, is it lether or Wool 
        if(jCheckBox_brzina.isSelected() ) haveDostupno_odmah=true;
        if(jCheckBox_vreme.isSelected() ) haveBrza_dostava=true;
        if(jCheck_leather.isSelected() ) haveKoža=true;
        if(jCheck_vul.isSelected() ) haveVuna=true;
        
        boolean Dostupno_odmah; 
        boolean Brza_dostava; 
        boolean Koža; 
        boolean Vuna;
        
        P_PLACE sale= new P_PLACE(0, Tip, Nacin_dostave, id_klijenta, Cena, Adresa_dostave, Kolicina_Proizvoda, Broj_razlicitih_materijala, Opis_komentar, haveDostupno_odmah, haveBrza_dostava, haveKoža, haveVuna);
        
        int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to add this sale","Added sale",JOptionPane.YES_NO_OPTION);
                if (yes_or_no == JOptionPane.YES_OPTION){
                    jTextField_Due_date.setText(sale.getNacin_dostave());
                jTextField_Client_id.setText(String.valueOf(sale.getid_klijenta()));
                jTextField_price.setText(String.valueOf(sale.getCena()));
                jTextArea_shipping_adress.setText(sale.getAdresa_dostave());
                jSpinner_kolicina.setValue(sale.getKolicina_Proizvoda());
                jSpinner_materijali.setValue(sale.getBroj_razlicitih_materijala());
                jTextArea_description.setText(sale.getOpis_komentar());
                 if(sale.isDostupno_odmah()) jCheckBox_brzina.setSelected(true); 
                 if(sale.isBrza_dostava()) jCheckBox_vreme.setSelected(true);    
                 if(sale.isKoža()) jCheck_leather.setSelected(true);
                 if(sale.isVuna()) jCheck_vul.setSelected(true);
        if (new P_PLACE().addnewsale(sale)){
            JOptionPane.showMessageDialog(null, "New sale added to system","Add sale", 1);
        }
        else {
                        JOptionPane.showMessageDialog(null, "Sale not added to system","Maybe fields are incorrect", 2);
                    }
                }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage()+ "Error ","Error", 0);
        }
        
    }//GEN-LAST:event_jButton_Add_online_saleActionPerformed

    private void jButton_show_online_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_online_saleActionPerformed
        Show_all_properties table = new Show_all_properties();
      table.setVisible(true);
      table.pack();
      table.setLocationRelativeTo(null);
      table.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButton_show_online_saleActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        //search and display sale data
        
        try {
            int saleid= Integer.valueOf(jTextField_id.getText());
            P_PLACE sale = new P_PLACE().searchnewsale(saleid);
            
            if (sale !=null){
                for(Object type : map.keySet()){
                    if (map.get(type).equals(sale.getTip()))
                        jComboBox_type.setSelectedItem(type);
                }
                jTextField_Due_date.setText(sale.getNacin_dostave());
                jTextField_Client_id.setText(String.valueOf(sale.getid_klijenta()));
                jTextField_price.setText(String.valueOf(sale.getCena()));
                jTextArea_shipping_adress.setText(sale.getAdresa_dostave());
                jSpinner_kolicina.setValue(sale.getKolicina_Proizvoda());
                jSpinner_materijali.setValue(sale.getBroj_razlicitih_materijala());
                jTextArea_description.setText(sale.getOpis_komentar());
                 if(sale.isDostupno_odmah()) jCheckBox_brzina.setSelected(true); 
                 if(sale.isBrza_dostava()) jCheckBox_vreme.setSelected(true);    
                 if(sale.isKoža()) jCheck_leather.setSelected(true);
                 if(sale.isVuna()) jCheck_vul.setSelected(true);
                 
            }else {
                JOptionPane.showMessageDialog(null,"Not found ","Error", 0);
            }
            
            
            
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage()+ "Error ","Error", 0);
        }
        
        
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRowIndex = jTable1.getSelectedRow();
        jTextArea_shipping_adress.setText(jTable1.getValueAt(selectedRowIndex, 5).toString());
        jTextArea_description.setText(jTable1.getValueAt(selectedRowIndex, 8).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_Export_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Export_allActionPerformed

         try {
            
                        int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want export all the values","Exported",JOptionPane.YES_NO_OPTION);
            if (yes_or_no == JOptionPane.YES_OPTION){
            
            
        
    PrintWriter pw= new PrintWriter(new File("C:\\Users\\marko\\Desktop\\online.txt"));
    StringBuilder sb=new StringBuilder();
    PreparedStatement ps;
    ResultSet rs=null;
 
    String query="select * from online_sale";
     ps = Connect_db.getTheconnection().prepareStatement(query);
    rs=ps.executeQuery();
 
    while(rs.next()){
     sb.append("ID: "); 
     sb.append(rs.getInt("id_proizvoda"));
     sb.append("   "); 
     sb.append("Tip: "); 
     sb.append(rs.getInt("Tip"));
     sb.append("   "); 
     sb.append("Nacin dostave: "); 
     sb.append(rs.getString("Nacin_dostave"));
     sb.append("   "); 
     sb.append("id klijenta: "); 
     sb.append(rs.getInt("id_klijenta"));
     sb.append("   "); 
     sb.append("Cena: "); 
     sb.append(rs.getString("Cena"));
     sb.append("   "); 
     sb.append("Adresa dostave: "); 
     sb.append(rs.getString("Adresa_dostave"));
     sb.append("   "); 
     sb.append("Kolicina Proizvoda: "); 
     sb.append(rs.getInt("Kolicina_Proizvoda"));
     sb.append("   "); 
     sb.append("Broj razlicitih materijala: "); 
     sb.append(rs.getInt("Broj_razlicitih_materijala"));
     sb.append("   "); 
     sb.append("Opis komentar: ");
     sb.append(rs.getString("Opis_komentar"));
     sb.append("   ");
     sb.append("Dostupno odmah: ");
     sb.append(rs.getBoolean("Dostupno_odmah"));
     sb.append("   ");
     sb.append("Brza dostava: ");
     sb.append(rs.getBoolean("Brza_dostava"));
     sb.append("   ");
     sb.append("Koža: ");
     sb.append(rs.getBoolean("Koža"));
     sb.append("   ");
     sb.append("Vuna: ");
     sb.append(rs.getBoolean("Vuna"));
     sb.append("\r\n");
    }
 
    pw.write(sb.toString());
    pw.close();
    System.out.println("finished");
    JOptionPane.showMessageDialog(null,"Exported all values to file ","Done", 0);
            }else {
            JOptionPane.showMessageDialog(null, "Ok","Next time maybe", 2);  
        }
            
   } catch (Exception e) {
    // TODO: handle exception
   }
    }//GEN-LAST:event_jButton_Export_allActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       Main_Window mainform = new Main_Window();
               mainform.setVisible(true);
               mainform.pack();
               mainform.setExtendedState(JFrame.MAXIMIZED_BOTH);  // to open in full screen
               //to close login window
               this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Placeholder1_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Placeholder1_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Placeholder1_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Placeholder1_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Placeholder1_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_online_sale;
    private javax.swing.JButton jButton_Edit_online_sale;
    private javax.swing.JButton jButton_Export_all;
    private javax.swing.JButton jButton_Remove_online_sale;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_show_online_sale;
    private javax.swing.JCheckBox jCheckBox_brzina;
    private javax.swing.JCheckBox jCheckBox_vreme;
    private javax.swing.JCheckBox jCheck_leather;
    private javax.swing.JCheckBox jCheck_vul;
    private javax.swing.JComboBox<String> jComboBox_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner_kolicina;
    private javax.swing.JSpinner jSpinner_materijali;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_description;
    private javax.swing.JTextArea jTextArea_shipping_adress;
    private javax.swing.JTextField jTextField_Client_id;
    private javax.swing.JTextField jTextField_Due_date;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_price;
    // End of variables declaration//GEN-END:variables
}
