
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author marko
 */
public class Placeholder_images_window extends javax.swing.JFrame {

    /**
     * Creates new form Placeholder_images_window
     */
    P_type type = new P_type();
    HashMap<String, Integer> map = type.getTypesMap();
    String sale_image_path = "";
    int proizvodid = 0;
    
    public Placeholder_images_window() {
        initComponents();
        
        // border for title of the panel
        Border panel_title_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(26,138,32));
        jPanel_title.setBorder(panel_title_border);
        
        // border for image jabel of the panel
        Border jLabel_image_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(26,138,32));
        jLabel_image.setBorder(jLabel_image_border);
        
        // border for jbuttons
        Border button_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(255,255,255));
        jButton_Add_image.setBorder(button_border);
        jButton_Show_image.setBorder(button_border);
        jButton_Remove_image.setBorder(button_border);
        
        fillJTableWithSalesData();
        bindCombo();
    }
     public void bindCombo(){
        
        
        
        for(String s : map.keySet())
        {
            jComboBox1.addItem(s);
        }
    }
     
     public void fillJTableWithSalesData(){
        P_PLACE sale = new P_PLACE();
        ArrayList<P_PLACE> saleList= sale.saleList();
        
        // the jtable columns
        String[] colNames= {"id_proizvoda","Adresa_dostave"};
        
        //the jtable row
        //workersList.size() size of arraylist
        //5 for number of colums in database
        Object[][] rows = new Object[saleList.size()][2];
        
        //add data from the list to the rows
        for(int i =0; i<saleList.size();i++){
            rows[i][0]=saleList.get(i).getid_proizvoda();
            rows[i][1]=saleList.get(i).getAdresa_dostave();
            
            
            
        }
        DefaultTableModel model =new DefaultTableModel(rows, colNames);
        jTable_products.setModel(model);
        //change jtable row height 
        jTable_products.setRowHeight(50);
        //background color when value selected
        jTable_products.setSelectionBackground(Color.green);
        //change jtable width
        jTable_products.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTable_products.getColumnModel().getColumn(1).setPreferredWidth(170);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Show_image = new javax.swing.JButton();
        jButton_Remove_image = new javax.swing.JButton();
        jButton_Add_image = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_products = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton_browse_image = new javax.swing.JButton();
        jLabel_image = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_title.setBackground(new java.awt.Color(255, 0, 0));
        jPanel_title.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(246, 145, 16));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Slike");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo3_2.jpg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1213, -1));

        jButton_Show_image.setBackground(new java.awt.Color(102, 0, 255));
        jButton_Show_image.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Show_image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Show_image.setText("Show image from this product");
        jButton_Show_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Show_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Show_imageActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Show_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 374, 61));

        jButton_Remove_image.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Remove_image.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Remove_image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove_image.setText("remove");
        jButton_Remove_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Remove_imageMouseClicked(evt);
            }
        });
        jButton_Remove_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Remove_imageActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Remove_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 261, 61));

        jButton_Add_image.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Add_image.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Add_image.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add_image.setText("add");
        jButton_Add_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_imageActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Add_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 401, 61));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select a type:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 133, 31));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 236, -1));

        jTable_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_products);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 374, 265));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select a image:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 128, 31));

        jButton_browse_image.setBackground(new java.awt.Color(255, 255, 51));
        jButton_browse_image.setText("browse");
        jButton_browse_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browse_imageActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_browse_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 129, 35));

        jLabel_image.setBackground(new java.awt.Color(255, 255, 204));
        jLabel_image.setText("                                    ");
        jLabel_image.setOpaque(true);
        jPanel1.add(jLabel_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 401, 265));

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 261, 265));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*This table contains id's of products");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 374, 31));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*This list contains image id of selected value");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 261, 31));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("*Select item from the list to display or browse your computer for image");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 600, 401, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Show_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Show_imageActionPerformed
      try{
          
          // set the image id
        int rowIndex = jTable_products.getSelectedRow(); // select jtable row index
        int id = Integer.valueOf(jTable_products.getValueAt(rowIndex, 0).toString());// get id from table
        //check if value has image. Using jList
        if (jList1.getModel().getSize()>0){
            //to show all  images
        Images_slider imagesSliderform = new Images_slider(id);
        
        
        
      imagesSliderform.setVisible(true);
      imagesSliderform.pack();
      imagesSliderform.setLocationRelativeTo(null);
      imagesSliderform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Select the value first that you want to show image of","Fail", 1);
        }
          
        
      }catch(Exception ex) {
           JOptionPane.showMessageDialog(null, "Select the value first that you want to show image of","Fail", 1);
       }
        
    }//GEN-LAST:event_jButton_Show_imageActionPerformed

    private void jButton_Remove_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_imageActionPerformed
      // remove image
        try{
        String selectedListItem = String.valueOf(jList1.getSelectedValue());
       Integer ImageId =Integer.valueOf(selectedListItem);
       int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to delete this image","Deleted image",JOptionPane.YES_NO_OPTION);
                

       if (yes_or_no == JOptionPane.YES_OPTION){

                    if(new P_PLACE().Removeimage(ImageId)) {
                        JOptionPane.showMessageDialog(null, "Slika uklonjen","Ukloniti Sliku", 1);
                        jLabel_image.setIcon(null);
           
       }else {
           JOptionPane.showMessageDialog(null, "Slika uklonjen","Ukloniti Sliku", 2);
       }
       }
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Error Error","Fail", 3);
        }
    }//GEN-LAST:event_jButton_Remove_imageActionPerformed

    private void jButton_Add_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_imageActionPerformed
       // to add images-- can add multiple
       try {
        P_PLACE image = new P_PLACE();
        
        if(proizvodid != 0){
            if(image.addImage(proizvodid, sale_image_path))
            {
            JOptionPane.showMessageDialog(null, "Image Added","Add Image", 1);
            }else {
            JOptionPane.showMessageDialog(null, "Image not Added","Not added Image", 2);
            }
        }else {
             JOptionPane.showMessageDialog(null, "Select value where to add image","Not added Image", 3);
        }
        
       }catch(Exception ex) {
           JOptionPane.showMessageDialog(null, "Select value where to add image","Not added Image", 4);
       }
    }//GEN-LAST:event_jButton_Add_imageActionPerformed
    
    //to make the image fit the label
    
    public ImageIcon resizeImage(String path, byte[] byteImage)
    {
        ImageIcon pic;
        if(byteImage != null){ 
            pic = new ImageIcon(byteImage);
        }
        else {
            pic = new ImageIcon(path);
        }
            Image img = pic.getImage().getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon image = new ImageIcon(img);
         return image;
        
        
    }
    
    private void jButton_browse_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browse_imageActionPerformed
        //look for a image from the computer
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select the image");
        fileChooser.setCurrentDirectory(new File("C:\\Images"));
        
        // file extension
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("images",".jpg",".png",".jpeg");
        fileChooser.addChoosableFileFilter(fileFilter);
        
        int fileState=fileChooser.showSaveDialog(null);
        
        if (fileState == JFileChooser.APPROVE_OPTION){
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            jLabel_image.setIcon(resizeImage(path, null));
            sale_image_path = path;
        }
        
    }//GEN-LAST:event_jButton_browse_imageActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         int ID_TP = map.get(jComboBox1.getSelectedItem().toString());
          P_PLACE propeties = new P_PLACE();
        ArrayList<P_PLACE> saleImages= propeties.saleImages(ID_TP);
        
        // the jtable columns
        String[] colNames= {"id_proizvoda","Adresa_dostave"};
        
        //the jtable row
        //workersList.size() size of arraylist
        //5 for number of colums in database
        Object[][] rows = new Object[saleImages.size()][2];
        
        //add data from the list to the rows
        for(int i =0; i<saleImages.size();i++){
            rows[i][0]=saleImages.get(i).getid_proizvoda();
            rows[i][1]=saleImages.get(i).getAdresa_dostave();
            
            
            
        }
        DefaultTableModel model =new DefaultTableModel(rows, colNames);
        jTable_products.setModel(model);
        //change jtable row height 
        jTable_products.setRowHeight(50);
        //background color when value selected
        jTable_products.setSelectionBackground(Color.green);
        //change jtable width
        jTable_products.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTable_products.getColumnModel().getColumn(1).setPreferredWidth(170);
        
         
         
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productsMouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable_products.getSelectedRow();
        proizvodid = Integer.valueOf(jTable_products.getValueAt(rowIndex , 0).toString());
        
        //display the selected value
        
        fillImagetable();
    }//GEN-LAST:event_jTable_productsMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        
        try {
       //display selected image from the list
       String selectedListItem = String.valueOf(jList1.getSelectedValue());
       Integer ImageId =Integer.valueOf(selectedListItem);
       byte[] image = new P_PLACE().getImagebyid(ImageId);
       jLabel_image.setIcon(resizeImage("",image));
        }
        catch(Exception ex) {
           
       }
       
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton_Remove_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Remove_imageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Remove_imageMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Main_Window mainform = new Main_Window();
               mainform.setVisible(true);
               mainform.pack();
               mainform.setExtendedState(JFrame.MAXIMIZED_BOTH);  // to open in full screen
               //to close login window
               this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    public void fillImagetable(){
        
        HashMap<byte[], Integer> imageListMap = new P_PLACE().showsaleImages(proizvodid);
        
        DefaultListModel listModel = new DefaultListModel();
        
        int i = 0;
        
        for (Integer id: imageListMap.values()) {
            listModel.add(i, id);
            i++;
        }
        
        jList1.setModel(listModel); 
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Placeholder_images_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Placeholder_images_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Placeholder_images_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Placeholder_images_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Placeholder_images_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_image;
    private javax.swing.JButton jButton_Remove_image;
    private javax.swing.JButton jButton_Show_image;
    private javax.swing.JButton jButton_browse_image;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_products;
    // End of variables declaration//GEN-END:variables
}
