
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.spire.data.table.DataTable;
import com.spire.data.table.common.JdbcAdapter;
import com.spire.pdf.PdfDocument;
import com.spire.pdf.PdfPageBase;
import com.spire.pdf.graphics.PdfBrush;
import com.spire.pdf.graphics.PdfBrushes;
import com.spire.pdf.graphics.PdfLayoutResult;
import com.spire.pdf.graphics.PdfLayoutType;
import com.spire.pdf.graphics.PdfStringFormat;
import com.spire.pdf.graphics.PdfTextAlignment;
import com.spire.pdf.graphics.PdfTrueTypeFont;
import com.spire.pdf.tables.PdfTable;
import com.spire.pdf.tables.PdfTableDataSourceType;
import com.spire.pdf.tables.PdfTableLayoutFormat;
import java.awt.Color;
import java.io.*;
import java.io.PrintWriter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import java.awt.geom.*;
import java.awt.*;
import java.sql.*;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author marko
 */
public class Postupak_Window extends javax.swing.JFrame {

    /**
     * Creates new form Postupak Window
     */
    public Postupak_Window() {
        initComponents();
        
         SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        jLabel14.setText(dFormat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        jLabel15.setText(dtf.format(now));
        
        // border for title of the panel
        Border panel_title_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(125,125,125));
        jPanel_title.setBorder(panel_title_border);
        
        // border for jbuttons
        Border button_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(255,255,255));
        jButton_Add.setBorder(button_border);
        jButton_Edit.setBorder(button_border);
        jButton_Remove.setBorder(button_border);
        jButton_Export_all.setBorder(button_border);
        fillJTableWithWorkersData();
    }
    //Function to populate the list
    
     public void fillJTableWithWorkersData(){
        Postupak_p worker = new Postupak_p();
        ArrayList<Postupak_p> workersList= worker.workersList();
        
        // the jtable columns
        String[] colNames= {"ID_Operacije","Naziv_operacije_rada","Vreme_trajanja_operacije_rada_min","Pripremno_zavrsno_vreme_tpz_min"};
        
        //the jtable row
        //workersList.size() size of arraylist
        //5 for number of colums in database
        Object[][] rows = new Object[workersList.size()][4];
        
        //add data from the list to the rows
        for(int i =0; i<workersList.size();i++){
            rows[i][0]=workersList.get(i).getID_Operacije();
            rows[i][1]=workersList.get(i).getNaziv_operacije_rada();
            rows[i][2]=workersList.get(i).getVreme_trajanja_operacije_rada_min();
            rows[i][3]=workersList.get(i).getPripremno_zavrsno_vreme_tpz_min();
            
        }
        DefaultTableModel model =new DefaultTableModel(rows, colNames);
        jTable1.setModel(model);
        //change jtable row height 
        jTable1.setRowHeight(50);
        //background color when value selected
        jTable1.setSelectionBackground(Color.red);
        //change jtable width
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(76);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(122);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(111);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Naziv_operacije_rada = new javax.swing.JTextField();
        jTextField_ID_Operacije = new javax.swing.JTextField();
        jTextField_Pripremno_zavrsno_vreme_tpz_min = new javax.swing.JTextField();
        jTextField_Vreme_trajanja_operacije_rada_min = new javax.swing.JTextField();
        jButton_Edit = new javax.swing.JButton();
        jButton_Remove = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jButton_Export_all = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel_title.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Potrebno vreme operacija");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo3_2.jpg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309)
                .addComponent(jLabel1)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Vreme_trajanja_operacije_rada_min:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("ID_Operacije:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Pripremno_zavrsno_vreme_tpz_min:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Naziv_operacije_rada:");

        jTextField_Vreme_trajanja_operacije_rada_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Vreme_trajanja_operacije_rada_minActionPerformed(evt);
            }
        });

        jButton_Edit.setBackground(new java.awt.Color(102, 0, 255));
        jButton_Edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Edit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Edit.setText("Edit");
        jButton_Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Remove.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Remove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Remove.setText("Remove");
        jButton_Remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveActionPerformed(evt);
            }
        });

        jButton_Add.setBackground(new java.awt.Color(255, 102, 102));
        jButton_Add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add.setText("Add");
        jButton_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Export_all.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Export_all.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Export_all.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Export_all.setText("Export all values");
        jButton_Export_all.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Export_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Export_allActionPerformed(evt);
            }
        });

        jLabel6.setText("Click on value to see everything thats within the value");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Date:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("jLabel3");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Time:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton_Export_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_Vreme_trajanja_operacije_rada_min, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Naziv_operacije_rada, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_ID_Operacije, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Pripremno_zavrsno_vreme_tpz_min, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addGap(213, 213, 213)))
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ID_Operacije, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Naziv_operacije_rada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Vreme_trajanja_operacije_rada_min, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Pripremno_zavrsno_vreme_tpz_min, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Export_all, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        // add new values also id auto increments
        try {
        String Naziv_operacije_rada = jTextField_Naziv_operacije_rada.getText();
        String a= jTextField_Vreme_trajanja_operacije_rada_min.getText();
        double Vreme_trajanja_operacije_rada_min= Double.parseDouble(a);
        String b= jTextField_Pripremno_zavrsno_vreme_tpz_min.getText();
        double Pripremno_zavrsno_vreme_tpz_min = Double.parseDouble(b);
        
        Postupak_p type = new Postupak_p(0, Naziv_operacije_rada, Vreme_trajanja_operacije_rada_min, Pripremno_zavrsno_vreme_tpz_min);
        int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to add this value","Added value",JOptionPane.YES_NO_OPTION);
            if (yes_or_no == JOptionPane.YES_OPTION){
        if (!Naziv_operacije_rada.trim().equals("")){// if the value is not empty
            if(type.execTypeQuery("Add", type)) {
            JOptionPane.showMessageDialog(null, "New value Added", "Add Value", 1);
            }else{
            JOptionPane.showMessageDialog(null, "Operation Failed", "Add Value", 2);
        }
        }
            }
        else {
            JOptionPane.showMessageDialog(null, "Enter a value", "Prazan naziv", 2);
        }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage()+ " Enter a valid Value", "Prazna su polja", 0);
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        // to edit selected values by typing the id of the value you want to edit
        try{
        Integer ID_Operacije = Integer.valueOf(jTextField_ID_Operacije.getText());
        String Naziv_operacije_rada = jTextField_Naziv_operacije_rada.getText();
        String a= jTextField_Vreme_trajanja_operacije_rada_min.getText();
        double Vreme_trajanja_operacije_rada_min= Double.parseDouble(a);
        String b= jTextField_Pripremno_zavrsno_vreme_tpz_min.getText();
        double Pripremno_zavrsno_vreme_tpz_min = Double.parseDouble(b);
        
        Postupak_p type = new Postupak_p(ID_Operacije, Naziv_operacije_rada, Vreme_trajanja_operacije_rada_min, Pripremno_zavrsno_vreme_tpz_min);
        int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to edit value","Edited value",JOptionPane.YES_NO_OPTION);
            if (yes_or_no == JOptionPane.YES_OPTION){
        if (!Naziv_operacije_rada.trim().equals("")){// if the value is not empty
            if(type.execTypeQuery("Edit", type)) {
            JOptionPane.showMessageDialog(null, "Value Updated", "Eit Value", 1);
            }else{
            JOptionPane.showMessageDialog(null, "Operation Failed", "Edit Value", 2);
        }
        }
            }
        else{
            JOptionPane.showMessageDialog(null, "Enter a value", "Prazan naziv", 2);
        }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage()+ " Enter a valid id to edit", "Prazna su polja", 0);
        }
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveActionPerformed
        // to remove value from specif id 
        
        try {
        Integer ID_Operacije = Integer.valueOf(jTextField_ID_Operacije.getText());
       
          
        
        Postupak_p type = new Postupak_p(ID_Operacije,"", 2.4, 3.2);
        
        if (!jTextField_ID_Operacije.getText().trim().equals("")){// if the value is not empty
            
            //show confirmation message before deleting the value
            int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want to delete this value","Deleted value",JOptionPane.YES_NO_OPTION);
            if (yes_or_no == JOptionPane.YES_OPTION){
                
            
            if(type.execTypeQuery("Remove", type)) {
            JOptionPane.showMessageDialog(null, "Value Deleted", "Delete Value", 1);
            }
            }else {
            JOptionPane.showMessageDialog(null, "Operation Failed don't enter id or fields are empty", "Delete Value", 2);
        }
        }
    else{
            JOptionPane.showMessageDialog(null, "Enter a value", "Prazan naziv", 2);
        }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage()+ " Enter a valid id to delete", "Prazna su polja", 0);
        }
    }//GEN-LAST:event_jButton_RemoveActionPerformed

    private void jButton_Export_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Export_allActionPerformed
        
        String id=jTextField_ID_Operacije.getText();
        String Naziv=jTextField_Naziv_operacije_rada.getText();
        String Vreme_trajanja=jTextField_Vreme_trajanja_operacije_rada_min.getText();
        String Pripremno_zavrsno=jTextField_Pripremno_zavrsno_vreme_tpz_min.getText();
        
        
        String path="C:\\Users\\marko\\Desktop\\Postupak.pdf";
        com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                                Krojac(Lista Zaposlenih)\n                                 Contact Number:(+381)111111\n\n");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("Date:"+jLabel14.getText()+"\n Time: "+jLabel15.getText()+"\n\n");
            doc.add(paragraph2);
            PdfPTable tbl = new PdfPTable(4);
            tbl.addCell("Id Operacije");
            tbl.addCell("Naziv operacije rada");
            tbl.addCell("Vreme trajanja operacije rada min");
            tbl.addCell("Pripremno zavrsno vreme tpz min");
            
            
            
            for (int i=0;i<jTable1.getRowCount();i++){
                String n=jTable1.getValueAt(i, 0).toString();
                String d=jTable1.getValueAt(i, 1).toString();
                String r=jTable1.getValueAt(i, 2).toString();
                String q=jTable1.getValueAt(i, 3).toString();
                
                
                tbl.addCell(n);
                tbl.addCell(d);
                tbl.addCell(r);
                tbl.addCell(q);
                
                
            }
            doc.add(tbl);
            Paragraph paragraph3= new Paragraph("\n\nThank you for Visiting !Please Come again\nKrojac");
            
            doc.add(paragraph3);
            JOptionPane.showMessageDialog(null,"Lista zaposlenih napravljena");
            setVisible(true);
            
            new Postupak_Window().setVisible(true);
            this.dispose();
            
        }catch (Exception e){
            
        }
        doc.close();
        /*
        try {
            
                        int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want export all the values","Exported",JOptionPane.YES_NO_OPTION);
            if (yes_or_no == JOptionPane.YES_OPTION){
            
            
        
    PrintWriter pw= new PrintWriter(new File("C:\\Users\\marko\\Desktop\\Operacija_rada.txt"));
    StringBuilder sb=new StringBuilder();
    PreparedStatement ps;
    ResultSet rs=null;
 
    String query="select * from operacija_rada";
     ps = Connect_db.getTheconnection().prepareStatement(query);
    rs=ps.executeQuery();
 
    while(rs.next()){
     sb.append("ID Operacije: "); 
     sb.append(rs.getInt("ID_Operacije"));
     sb.append("   "); 
     sb.append("Naziv operacije rada: ");
     sb.append(rs.getString("Naziv_operacije_rada"));
     sb.append("   ");
     sb.append("Vreme trajanja operacije rada min: ");
     sb.append(rs.getDouble("Vreme_trajanja_operacije_rada_min"));
     sb.append("   ");
     sb.append("Pripremno zavrsno vreme tpz min: ");
     sb.append(rs.getDouble("Pripremno_zavrsno_vreme_tpz_min"));
     sb.append("\r\n");
    }
 
    pw.write(sb.toString());
    pw.close();
    System.out.println("finished");
    JOptionPane.showMessageDialog(null,"Exported all values to file ","Done", 0);
            }else {
            JOptionPane.showMessageDialog(null, "Ok","Next time maybe", 2);  
        }
            
   } catch (Exception e) {
    // TODO: handle exception
   }
        */
    }//GEN-LAST:event_jButton_Export_allActionPerformed

    private void jTextField_Vreme_trajanja_operacije_rada_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Vreme_trajanja_operacije_rada_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Vreme_trajanja_operacije_rada_minActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       Main_Window mainform = new Main_Window();
               mainform.setVisible(true);
               mainform.pack();
               mainform.setExtendedState(JFrame.MAXIMIZED_BOTH);  // to open in full screen
               //to close login window
               this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Postupak_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Postupak_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Postupak_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Postupak_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Postupak_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Export_all;
    private javax.swing.JButton jButton_Remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_ID_Operacije;
    private javax.swing.JTextField jTextField_Naziv_operacije_rada;
    private javax.swing.JTextField jTextField_Pripremno_zavrsno_vreme_tpz_min;
    private javax.swing.JTextField jTextField_Vreme_trajanja_operacije_rada_min;
    // End of variables declaration//GEN-END:variables
}
