
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.PrintStream;
import java.io.*;
import static java.nio.file.Files.write;
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.imageio.ImageIO.write;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author marko
 */
public class Proizvodi_Window extends javax.swing.JFrame {
public int finalTotal=0;
    /**
     * Creates new form Zaposleni_Window
     */
    public Proizvodi_Window() {
        initComponents();
        
        SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date date = new java.util.Date();
        jLabel28.setText(dFormat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        jLabel31.setText(dtf.format(now));
        
         // border for title of the panel
        Border panel_title_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(60,70,200));
        jPanel_title.setBorder(panel_title_border);
        
        // border for jbuttons
        
        
        
        //populate the table
        fillJTableWithClientsData();
    }

    //function to populate jtable with all the values in zaposleni
   public Double[] fillJTableWithClientsData(){
        Proizvodi_p proizvod = new Proizvodi_p();
        ArrayList<Proizvodi_p> productsList= proizvod.productsList();
        
        // the jtable columns
        String[] colNames= {"id","min","Krojaci","Magacioneri","kWh","Konac","Keper","Strec","Guma","Celicni_kalup","Makaze","Stoni_metar","Pribor_za_pisanje","Stancer","Masina_za_sivenje","Masina_za_endlanje","Masina_za_tabanicenje","Proizvod"};
        
        //the jtable row
        //workersList.size() size of arraylist
        //5 for number of colums in database
        Double[] rows = new Double[17];
        
        //add data from the list to the rows
        for(int i=0; i<productsList.size();i++){
            rows[1]=productsList.get(i).getId();
            rows[1]=productsList.get(i).getMin();
            rows[2]=productsList.get(i).getKrojaci();
            rows[3]=productsList.get(i).getMagacioneri();
            rows[4]=productsList.get(i).getkWh();
            rows[5]=productsList.get(i).getKonac();
            rows[6]=productsList.get(i).getKeper();
            rows[7]=productsList.get(i).getStrec();
            rows[8]=productsList.get(i).getGuma();
            rows[9]=productsList.get(i).getCelicni_kalup();
            rows[10]=productsList.get(i).getMakaze();
            rows[11]=productsList.get(i).getStoni_metar();
            rows[12]=productsList.get(i).getPribor_za_pisanje();
            rows[13]=productsList.get(i).getStancer();
            rows[14]=productsList.get(i).getMasina_za_sivenje();
            rows[15]=productsList.get(i).getMasina_za_endlanje();
            rows[16]=productsList.get(i).getMasina_za_tabanicenje();
            
        }
       
        
       
    return rows;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Kolicina = new javax.swing.JTextField();
        jButton_check_price = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_export = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Masina_za_endlanje = new javax.swing.JTextField();
        jTextField_Magacioneri = new javax.swing.JTextField();
        jTextField_Krojaci = new javax.swing.JTextField();
        jTextField_Stoni_metar = new javax.swing.JTextField();
        jTextField_Masina_za_tabanicenje = new javax.swing.JTextField();
        jTextField_Strec = new javax.swing.JTextField();
        jTextField_Guma = new javax.swing.JTextField();
        jTextField_Konac = new javax.swing.JTextField();
        jTextField_Celicni_kalup = new javax.swing.JTextField();
        jTextField_Stancer = new javax.swing.JTextField();
        jTextField_Keper = new javax.swing.JTextField();
        jTextField_Masina_za_sivenje = new javax.swing.JTextField();
        jTextField_kWh = new javax.swing.JTextField();
        jTextField_Pribor_za_pisanje = new javax.swing.JTextField();
        jTextField_Makaze = new javax.swing.JTextField();
        jTextField_min = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jPanel_title.setBackground(new java.awt.Color(96, 90, 223));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proizvodi");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo3_2.jpg"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Date:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("jLabel3");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Time:");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("jLabel4");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_titleLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28))
                    .addGroup(jPanel_titleLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)))
                .addGap(48, 48, 48))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_titleLayout.createSequentialGroup()
                        .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Helanke", "Baletanke" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(204, 204, 255)));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Izaberi proizvod");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Kolicina");

        jTextField_Kolicina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_KolicinaMouseClicked(evt);
            }
        });

        jButton_check_price.setText("Check price for entered amount");
        jButton_check_price.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_check_price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_check_priceMouseClicked(evt);
            }
        });
        jButton_check_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_check_priceActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton_export.setText("Export all to pdf");
        jButton_export.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_export.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_exportMouseClicked(evt);
            }
        });
        jButton_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Kolicina)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_check_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(jButton_export, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Kolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_check_price, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton_export, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Neophodni resorsi za proizvodnju");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Potrebni Radnici");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Potrebno Vreme");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Potrebne masine");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Potreban pribor");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Potrebna energija");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Potrebni materijali");

        jLabel2.setText("Keper");

        jLabel10.setText("Konac");

        jLabel13.setText("Strec");

        jLabel14.setText("Guma");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Celicni kalup");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Makaze");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Stoni metar");

        jLabel18.setText("Pribor za pisanje");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Stancer");

        jLabel20.setText("Masina za endlanje");

        jLabel21.setText("Masina za tabanicenje");

        jLabel22.setText("Masina za sivenje");

        jLabel23.setText("kWh");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("min");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Krojaci");

        jLabel26.setText("Magacioneri");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_Keper, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(jTextField_Konac)
                                            .addComponent(jTextField_Strec)
                                            .addComponent(jTextField_Guma))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_Magacioneri)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_Krojaci, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_Stoni_metar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField_Celicni_kalup)
                                        .addComponent(jTextField_Makaze)
                                        .addComponent(jTextField_Pribor_za_pisanje)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_min, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_kWh, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Stancer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Masina_za_tabanicenje, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Masina_za_sivenje, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Masina_za_endlanje, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_kWh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel24)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Konac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Keper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Strec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_Guma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Stancer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Masina_za_sivenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Masina_za_endlanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Masina_za_tabanicenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(64, 64, 64))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Krojaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Magacioneri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Celicni_kalup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Makaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Stoni_metar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Pribor_za_pisanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_check_priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_check_priceMouseClicked
     /*String paidAmount=jTextField_Kolicina.getText();
        int z=Integer.parseInt(paidAmount);
        finalTotal=z-finalTotal;
        String finalTotal1=String.valueOf(finalTotal);
        jTextField_min.setText(finalTotal1);
        jTextField_min.setEditable(false);
        */
        
        
    
        
        
       /*
        double min = Double.valueOf(jTextField_min.getText());
        
        
        int Krojaci = Integer.valueOf(jTextField_Krojaci.getText());
        
        int Magacioneri= Integer.valueOf(jTextField_Magacioneri.getText());
        
        double kWh = Double.valueOf(jTextField_kWh.getText());
        
        int Konac= Integer.valueOf(jTextField_Konac.getText());
        
        int Keper = Integer.valueOf(jTextField_Keper.getText());
        
        int Strec= Integer.valueOf(jTextField_Strec.getText());
       
        int Guma = Integer.valueOf(jTextField_Guma.getText());
       
        int Celicni_kalup= Integer.valueOf(jTextField_Celicni_kalup.getText());
        
        int Makaze = Integer.valueOf(jTextField_Makaze.getText());
        
        int Stoni_metar= Integer.valueOf(jTextField_Stoni_metar.getText());
        
        int Pribor_za_pisanje = Integer.valueOf(jTextField_Pribor_za_pisanje.getText());
        
        int Stancer= Integer.valueOf(jTextField_Stancer.getText());
        
        int Masina_za_sivenje = Integer.valueOf(jTextField_Masina_za_sivenje.getText());
        
        int Masina_za_endlanje= Integer.valueOf(jTextField_Masina_za_endlanje.getText());
        
        int Masina_za_tabanicenje = Integer.valueOf(jTextField_Masina_za_tabanicenje.getText());
        String proizvod= jTextField_products.getText();
        int v17;
        v17 = Integer.valueOf(jTextField_Kolicina.getText());
        Double v1=14.280001;
       Double v1_1=16.45;
        
        Proizvodi_p products= new Proizvodi_p(0, min, Krojaci, Magacioneri, kWh, Konac, Keper, Strec, Guma, Celicni_kalup, Makaze, Stoni_metar, Pribor_za_pisanje,Stancer,Masina_za_sivenje,Masina_za_endlanje,Masina_za_tabanicenje,proizvod);
        
        
        double v2=min;
        int v3 = Krojaci;
        int v4 = Magacioneri;
        double v5=kWh;
        int v6 = Konac;
        int v7 = Keper;
        int v8 = Strec;
        int v9 = Guma;
        int v10 = Celicni_kalup;
        int v11 = Makaze;
        int v12 = Stoni_metar;
        int v13= Pribor_za_pisanje;
        int v14 = Stancer;
        int v15 = Masina_za_sivenje;
        int v16= Masina_za_endlanje;
        int v18= Masina_za_tabanicenje;
        
        
       
        /*
         ps.setInt(1, id);
         ps.setDouble(2, min);
         ps.setInt(3, Krojaci);
         ps.setInt(4, Magacioneri);
         ps.setDouble(5, kWh);
         ps.setInt(6, Konac);
         ps.setInt(7, Keper);
         ps.setInt(8, Strec);
         ps.setInt(9, Guma);
         ps.setInt(10, Celicni_kalup);
         ps.setInt(11, Makaze);
         ps.setInt(12, Stoni_metar);
         ps.setInt(13, Pribor_za_pisanje);
         ps.setInt(14, Stancer);
         ps.setInt(15, Masina_za_sivenje);
         ps.setInt(16, Masina_za_endlanje);
         ps.setString(17, proizvod);
        */
        
        
        
        
        
        
        
        
        
        
        
        
        
        //whole code is a test to trying out later with database
        // try figure out what formulas you want to use etc
        //example one krojac can do like certain amount of work or for machines etc.
        //1 = 25 products
        
     /*
       Double v17;
       Double v1=14.280001;
       Double v1_1=16.45;
        v17 = Double.valueOf(jTextField_Kolicina.getText());
        int v2=6;
        int v3=4;
        int v4=10;
        int v5=20;
        int v6=500;
        int v7=200;
        int v8=100;
        int v9=4;
        int v10=6;
        int v11=14;
        int v12=13;
        int v13=4;
        int v14=6;
        int v15=7;
        int v16=6;
       
       
      Double result1,result1_1,result2,result5,result3,result4,result6,result7,result8,result9,result10,result11,result12,result13,result14,result15,result16;
      
      result1= v1*v17;
      if (v17>25){
          result2= v17/25;
      }else {
          result2=1.0;
      }
      if (v17>25){
          result3= (v17/25);
      }else {
          result3=1.0;
      }
      result4= v4*v17;
      result5= v5*v17;
      result6=  v6*v17;
      result7= v7*v17;
      result8= v8*v17;
      if (v17>25){
          result9= v17/25;
      }else {
          result9=1.0;
      }
      if (v17>25){
          result10=v17/25;
      }else {
          result10=1.0;
      }
            if (v17>25){
          result11= v17/25;
      }else {
          result11=1.0;
      }
      if (v17>25){
          result12= v17/25;
      }else {
          result12=1.0;
      }
            if (v17>25){
          result13= v17/25;
      }else {
          result13=1.0;
      }
      if (v17>25){
          result14= v17/25;
      }else {
          result14=1.0;
      }
            if (v17>25){
          result15= v17/25;
      }else {
          result15=1.0;
      }
      if (v17>25){
          result16= v17/25;
      }else {
          result16=1.0;
      }
      
      result1_1= v1_1*v17;
      
      if (jComboBox1.getSelectedItem(). equals("Helanke")){
      jTextField_min.setText(""+result1);
      jTextField_Krojaci.setText(""+result2);
      jTextField_Magacioneri.setText(""+result3);
      jTextField_kWh.setText(""+result4);
      jTextField_Konac.setText(""+result5);
      jTextField_Keper.setText(""+result6);
      jTextField_Strec.setText(""+result7);
      jTextField_Guma.setText(""+result8);
      jTextField_Celicni_kalup.setText(""+result9);
      jTextField_Makaze.setText(""+result10);
      jTextField_Stoni_metar.setText(""+result11);
      jTextField_Pribor_za_pisanje.setText(""+result12);
      jTextField_Stancer.setText(""+result13);
      jTextField_Masina_za_sivenje.setText(""+result14);
      jTextField_Masina_za_endlanje.setText(""+result15);
      jTextField_Masina_za_tabanicenje.setText(""+result16);
      }else {
      jTextField_min.setText(""+result1_1);
      jTextField_Krojaci.setText(""+result2);
      jTextField_Magacioneri.setText(""+result3);
      jTextField_kWh.setText(""+result4);
      jTextField_Konac.setText(""+result5);
      jTextField_Keper.setText(""+result6);
      jTextField_Strec.setText(""+result7);
      jTextField_Guma.setText(""+result8);
      jTextField_Celicni_kalup.setText(""+result9);
      jTextField_Makaze.setText(""+result10);
      jTextField_Stoni_metar.setText(""+result11);
      jTextField_Pribor_za_pisanje.setText(""+result12);
      jTextField_Stancer.setText(""+result13);
      jTextField_Masina_za_sivenje.setText(""+result14);
      jTextField_Masina_za_endlanje.setText(""+result15);
      jTextField_Masina_za_tabanicenje.setText(""+result16);
      }
        
        */
    }//GEN-LAST:event_jButton_check_priceMouseClicked

    private void jTextField_KolicinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_KolicinaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_KolicinaMouseClicked

    private void jButton_check_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_check_priceActionPerformed
        
        Double[] rows =  fillJTableWithClientsData();
        // v1 je min, v2 je Krojaci, v3 su Magacioneri, v4 kWh, itd sve do v16 posle je proizvod a pre min je id
        
        double v1_1=14.28000001;
        double v1 = rows[1];
        double v2 = rows[2];
        double v3 = rows[3];
        double v4 = rows[4];
        double v5 = rows[5];
        double v6 =  rows[6];
        double v7 =  rows[7];
        double v8 = rows[8];
        double v9 =  rows[9];
        double v10 =  rows[10];
        double v11 =  rows[11];
        double v12 =  rows[12];
        double v13 =  rows[13];
        double v14 =  rows[14];
        double v15 =  rows[15];
        double v16 =  rows[16];
        Double v17;
       v17 = Double.valueOf(jTextField_Kolicina.getText());
        Double result1,result1_1,result2,result5,result3,result4,result6,result7,result8,result9,result10,result11,result12,result13,result14,result15,result16;
        
         result1= v1*v17;
      if (v17>25){
          result2= v17/25;
      }else {
          result2=1.0;
      }
      if (v17>25){
          result3= (v17/25);
      }else {
          result3=1.0;
      }
      result4= v4*v17;
      result5= v5*v17;
      result6=  v6*v17;
      result7= v7*v17;
      result8= v8*v17;
      if (v17>25){
          result9= v17/25;
      }else {
          result9=1.0;
      }
      if (v17>25){
          result10=v17/25;
      }else {
          result10=1.0;
      }
            if (v17>25){
          result11= v17/25;
      }else {
          result11=1.0;
      }
      if (v17>25){
          result12= v17/25;
      }else {
          result12=1.0;
      }
            if (v17>25){
          result13= v17/25;
      }else {
          result13=1.0;
      }
      if (v17>25){
          result14= v17/25;
      }else {
          result14=1.0;
      }
            if (v17>25){
          result15= v17/25;
      }else {
          result15=1.0;
      }
      if (v17>25){
          result16= v17/25;
      }else {
          result16=1.0;
      }
       result1_1= v1_1 * v17;
      
      
      
      
      if (jComboBox1.getSelectedItem(). equals("Helanke")){
      jTextField_min.setText(""+result1);
      jTextField_Krojaci.setText(""+result2);
      jTextField_Magacioneri.setText(""+result3);
      jTextField_kWh.setText(""+result4);
      jTextField_Konac.setText(""+result5);
      jTextField_Keper.setText(""+result6);
      jTextField_Strec.setText(""+result7);
      jTextField_Guma.setText(""+result8);
      jTextField_Celicni_kalup.setText(""+result9);
      jTextField_Makaze.setText(""+result10);
      jTextField_Stoni_metar.setText(""+result11);
      jTextField_Pribor_za_pisanje.setText(""+result12);
      jTextField_Stancer.setText(""+result13);
      jTextField_Masina_za_sivenje.setText(""+result14);
      jTextField_Masina_za_endlanje.setText(""+result15);
      jTextField_Masina_za_tabanicenje.setText(""+result16);
      }else if (jComboBox1.getSelectedItem(). equals("Baletanke")) {
      jTextField_min.setText(""+result1_1);
      jTextField_Krojaci.setText(""+result2);
      jTextField_Magacioneri.setText(""+result3);
      jTextField_kWh.setText(""+result4);
      jTextField_Konac.setText(""+result5);
      jTextField_Keper.setText(""+result6);
      jTextField_Strec.setText(""+result7);
      jTextField_Guma.setText(""+result8);
      jTextField_Celicni_kalup.setText(""+result9);
      jTextField_Makaze.setText(""+result10);
      jTextField_Stoni_metar.setText(""+result11);
      jTextField_Pribor_za_pisanje.setText(""+result12);
      jTextField_Stancer.setText(""+result13);
      jTextField_Masina_za_sivenje.setText(""+result14);
      jTextField_Masina_za_endlanje.setText(""+result15);
      jTextField_Masina_za_tabanicenje.setText(""+result16);
      }
        
    }//GEN-LAST:event_jButton_check_priceActionPerformed

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        Main_Window mainform = new Main_Window();
               mainform.setVisible(true);
               mainform.pack();
               mainform.setExtendedState(JFrame.MAXIMIZED_BOTH);  // to open in full screen
               //to close login window
               this.dispose();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jButton_exportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_exportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_exportMouseClicked

    private void jButton_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exportActionPerformed
      
         try {
               Double[] rows =  fillJTableWithClientsData();
        // v1 je min, v2 je Krojaci, v3 su Magacioneri, v4 kWh, itd sve do v16 posle je proizvod a pre min je id
        
        double v1_1=14.28000001;
        double v1 = rows[1];
        double v2 = rows[2];
        double v3 = rows[3];
        double v4 = rows[4];
        double v5 = rows[5];
        double v6 =  rows[6];
        double v7 =  rows[7];
        double v8 = rows[8];
        double v9 =  rows[9];
        double v10 =  rows[10];
        double v11 =  rows[11];
        double v12 =  rows[12];
        double v13 =  rows[13];
        double v14 =  rows[14];
        double v15 =  rows[15];
        double v16 =  rows[16];
        Double v17;
       v17 = Double.valueOf(jTextField_Kolicina.getText());
        Double result1,result1_1,result2,result5,result3,result4,result6,result7,result8,result9,result10,result11,result12,result13,result14,result15,result16;
        
         result1= v1*v17;
      if (v17>25){
          result2= v17/25;
      }else {
          result2=1.0;
      }
      if (v17>25){
          result3= (v17/25);
      }else {
          result3=1.0;
      }
      result4= v4*v17;
      result5= v5*v17;
      result6=  v6*v17;
      result7= v7*v17;
      result8= v8*v17;
      if (v17>25){
          result9= v17/25;
      }else {
          result9=1.0;
      }
      if (v17>25){
          result10=v17/25;
      }else {
          result10=1.0;
      }
            if (v17>25){
          result11= v17/25;
      }else {
          result11=1.0;
      }
      if (v17>25){
          result12= v17/25;
      }else {
          result12=1.0;
      }
            if (v17>25){
          result13= v17/25;
      }else {
          result13=1.0;
      }
      if (v17>25){
          result14= v17/25;
      }else {
          result14=1.0;
      }
            if (v17>25){
          result15= v17/25;
      }else {
          result15=1.0;
      }
      if (v17>25){
          result16= v17/25;
      }else {
          result16=1.0;
      }
       result1_1= v1_1 * v17;
      
            
                        int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You want export all the values","Exported",JOptionPane.YES_NO_OPTION);
            if (yes_or_no == JOptionPane.YES_OPTION){
            
            
        
    PrintWriter pw= new PrintWriter(new File("C:\\Users\\marko\\Desktop\\prodaja.txt"));
    StringBuilder sb=new StringBuilder();
    
 
     if (jComboBox1.getSelectedItem(). equals("Helanke")){
     sb.append("min: "); 
     sb.append(result1);
     sb.append("   "); 
     sb.append("Krojaci: "); 
     sb.append(result2);
     sb.append("   "); 
     sb.append("Magacioneri: "); 
     sb.append(result3);
     sb.append("   "); 
     sb.append("kWh: "); 
     sb.append(result4);
     sb.append("   "); 
     sb.append("konac: "); 
     sb.append(result5);
     sb.append("   "); 
     sb.append("keper: "); 
     sb.append(result6);
     sb.append("   "); 
     sb.append("Strec: "); 
     sb.append(result7);
     sb.append("   "); 
     sb.append("Guma: "); 
     sb.append(result8);
     sb.append("   "); 
     sb.append("Celicni kalup: ");
     sb.append(result9);
     sb.append("   ");
     sb.append("Makaze: ");
     sb.append(result10);
     sb.append("   ");
     sb.append("Stoni metar: ");
     sb.append(result11);
     sb.append("   ");
     sb.append("Pribor za pisanje: ");
     sb.append(result12);
     sb.append("   ");
     sb.append("Masine stancer: ");
     sb.append(result13);
     sb.append("   ");
     sb.append("masina za sivenje: ");
     sb.append(result14);
     sb.append("   ");
     sb.append("Masina za endlanje: ");
     sb.append(result15);
     sb.append("   ");
     sb.append("Masina za tabanicenje: ");
     sb.append(result16);
     sb.append("\r\n");
     }
     else if (jComboBox1.getSelectedItem(). equals("Baletanke")) {
         sb.append("min: "); 
     sb.append(result1_1);
     sb.append("   "); 
     sb.append("Krojaci: "); 
     sb.append(result2);
     sb.append("   "); 
     sb.append("Magacioneri: "); 
     sb.append(result3);
     sb.append("   "); 
     sb.append("kWh: "); 
     sb.append(result4);
     sb.append("   "); 
     sb.append("konac: "); 
     sb.append(result5);
     sb.append("   "); 
     sb.append("keper: "); 
     sb.append(result6);
     sb.append("   "); 
     sb.append("Strec: "); 
     sb.append(result7);
     sb.append("   "); 
     sb.append("Guma: "); 
     sb.append(result8);
     sb.append("   "); 
     sb.append("Celicni kalup: ");
     sb.append(result9);
     sb.append("   ");
     sb.append("Makaze: ");
     sb.append(result10);
     sb.append("   ");
     sb.append("Stoni metar: ");
     sb.append(result11);
     sb.append("   ");
     sb.append("Pribor za pisanje: ");
     sb.append(result12);
     sb.append("   ");
     sb.append("Masine stancer: ");
     sb.append(result13);
     sb.append("   ");
     sb.append("masina za sivenje: ");
     sb.append(result14);
     sb.append("   ");
     sb.append("Masina za endlanje: ");
     sb.append(result15);
     sb.append("   ");
     sb.append("Masina za tabanicenje: ");
     sb.append(result16);
     sb.append("\r\n");
     }
    
 
    pw.write(sb.toString());
    pw.close();
    System.out.println("finished");
    JOptionPane.showMessageDialog(null,"Exported all values to file ","Done", 0);
            }else {
            JOptionPane.showMessageDialog(null, "Ok","Next time maybe", 2);  
        }
            
   } catch (Exception e) {
    // TODO: handle exception
   }
    }//GEN-LAST:event_jButton_exportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zaposleni_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zaposleni_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zaposleni_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zaposleni_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proizvodi_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_check_price;
    private javax.swing.JButton jButton_export;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Celicni_kalup;
    private javax.swing.JTextField jTextField_Guma;
    private javax.swing.JTextField jTextField_Keper;
    private javax.swing.JTextField jTextField_Kolicina;
    private javax.swing.JTextField jTextField_Konac;
    private javax.swing.JTextField jTextField_Krojaci;
    private javax.swing.JTextField jTextField_Magacioneri;
    private javax.swing.JTextField jTextField_Makaze;
    private javax.swing.JTextField jTextField_Masina_za_endlanje;
    private javax.swing.JTextField jTextField_Masina_za_sivenje;
    private javax.swing.JTextField jTextField_Masina_za_tabanicenje;
    private javax.swing.JTextField jTextField_Pribor_za_pisanje;
    private javax.swing.JTextField jTextField_Stancer;
    private javax.swing.JTextField jTextField_Stoni_metar;
    private javax.swing.JTextField jTextField_Strec;
    private javax.swing.JTextField jTextField_kWh;
    private javax.swing.JTextField jTextField_min;
    // End of variables declaration//GEN-END:variables
}
